apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-sync-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-sync
  template:
    metadata:
      labels:
        app: s3-sync
    spec:
      containers:
      - name: s3-sync-container
        image: victor-utsc/proyecto-cloud-k8s:latest # Asegúrate que este sea el nombre de tu imagen
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: credenciales-aws
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: credenciales-aws
              key: secret-key
        volumeMounts:
        - name: config-volume
          mountPath: /app/mi_nube
      volumes:
      - name: config-volume
        hostPath:
          path: /home/victor/proyecto-cloud