apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-sync-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-sync
  template:
    metadata:
      labels:
        app: s3-sync
    spec:
      containers:
      - name: sync-container
        image: v1ctor2121/s3-sync:latest
        imagePullPolicy: Always
        env:
        volumeMounts:
    - name: volumen-windows
      mountPath: /app/mi_nube
  volumes:
  - name: volumen-windows
    hostPath:
      path: /mnt/mi_nube_windows  # <-- La ruta que acabamos de conectar
      type: Directory
        # Aquí van tus credenciales de IAM en AWS
        - name: PYTHONUNBUFFERED      # <--- Obliga a mostrar logs
          value: "1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: credenciales-aws
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: credenciales-aws
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: "us-east-2"
